[versions]
# Library versions
coil = "3.3.0"
desugarLibVersion = "2.1.5"
koin = "4.1.1"
fuzzywuzzy = "1.4.0"
guavaVersion = "31.1-android" # To prevent Guava conflict, use this old version

#  Google Libraries
androidxAppCompat = "1.7.1"
androidxCore = "1.17.0"
androidxActivity = "1.11.0"
androidxPreference = "1.2.1"
androidxBrowser = "1.9.0"
materialDesign = "1.13.0"
androidxDataStore = "1.1.7"
paging = "3.3.6"
barcodeScanner = "17.3.0"

# Jetpack Compose
composeBom = "2025.10.00" # TODO: check the TextInput focus issue in newer version
lifecycleCompose = "2.9.4"
navigationCompose = "2.9.5"
constraintlayoutCompose = "1.1.1"
requestPermissionCompose = "1.3.2"
webviewCompose = "0.33.6"

# CameraX
viewFinderCompose = "1.5.1"
cameraXVersion = "1.5.1"

#  Kotlin Libraries
kotlinxCoroutines = "1.10.2"
kotlinxSerializationJson = "1.9.0"
datetime = "0.7.1"
ktor = "3.3.1"
immutableCollections = "0.4.0"

#  Google Service and Firebase Libraries
firebaseBom = "33.15.0"
admob = "24.3.0"
inAppReview = "2.0.2"

#  Test related
androidxTestExt = "1.3.0"
androidxTestRunner = "1.7.0"
androidxTestCore = "1.7.0"
androidxEspresso = "3.7.0"

# plugins versions
androidGradlePlugin = "8.10.1"
kotlin = "2.2.21"
gmsPlugin = "4.4.2"
firebaseCrashlyticsPlugin = "3.0.4"
firebaseAppDistributionPlugin = "5.1.1"
detektVersion = "1.23.8"
ktlintGradle = "12.3.0"
sqldelight = "2.1.0"
uiAndroid = "1.7.1"
spotless = "8.0.0"
ktlintCli = "1.7.1"

[libraries]
coil-kt = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose-navigation" }
fuzzywuzzy = { group = "me.xdrop", name = "fuzzywuzzy", version.ref = "fuzzywuzzy" }
detekt-ktlint-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detektVersion" }
detekt-cli = { group = "io.gitlab.arturbosch.detekt", name = "detekt-cli", version.ref = "detektVersion" }
sqldelight-android-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-paging3-extensions = { group = "app.cash.sqldelight", name = "androidx-paging3-extensions", version.ref = "sqldelight" }
guava-android = { group = "com.google.guava", name = "guava", version.ref = "guavaVersion" }
spotless-gradle-plugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }

#  Google
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarLibVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity", version.ref = "androidxActivity" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreference" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialDesign" }
androidx-dataStore-core = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-lifecycle-runtime-compose-android = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose-android", version.ref = "lifecycleCompose" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "barcodeScanner" }

# Jetpack Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
compose-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleCompose" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
compose-ui-android = { group = "androidx.compose.ui", name = "ui-android" }
compose-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive" }
compose-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout" }
compose-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
request-permission-compose = { group = "com.github.MshariAlsayari", name = "Request-Permission-Compose", version.ref = "requestPermissionCompose" }
webview-compose = { group = "io.github.kevinnzou", name = "compose-webview", version.ref = "webviewCompose" }

# CameraX
viewfinder-compose = { group = "androidx.camera.viewfinder", name = "viewfinder-compose", version.ref = "viewFinderCompose" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraXVersion" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraXVersion" }

#  Kotlin
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutableCollections" }

#  Google Service and Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
admob = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "admob" }
play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "inAppReview" }

#  Test related
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-app-distribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistributionPlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVersion" }
ktlintGradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
